site_name: Pydantic-resolve
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.tabs.sticky

repo_name: allmonday/pydantic-resolve
repo_url: https://github.com/allmonday/pydantic-resolve
edit_uri: ""

nav:
  - Quick Start:
      - Install: ./v1/index.md
      - Let's start: ./v1/about.md
      - Dataloader: ./v1/dataloader.md
      - Inheritance: ./v1/inherit.md
      - Tree: ./v1/tree.md
      - Philosophy: ./v1/philosophy.md
  - Reference:
      - API: ./v1/reference_api.md
  - Change log:
      - pydantic-resolve: ./v1/changelog.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences

plugins:
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          default: true
          name: English
          build: true
          link: "/pydantic-resolve/"
        - locale: zh
          name: 中文
          build: true
          link: "/pydantic-resolve/zh/"
          nav_translations:
            Quick Start: "快速开始"
            Reference: "文档"
            Change log: "变更记录"
            Install: "安装"
            Let's start: "开始"
            Inheritance: "继承"
            Philosophy: "迷思"
