site_name: Pydantic-resolve
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.tabs.sticky

repo_name: allmonday/pydantic-resolve
repo_url: https://github.com/allmonday/pydantic-resolve
edit_uri: ""

# nav:
#   - Quick Start:
#       - Install: ./v1/index.md
#       - Let's start: ./v1/about.md
#       - Dataloader: ./v1/dataloader.md
#       - Inheritance: ./v1/inherit.md
#       - Tree: ./v1/tree.md
#       - Philosophy: ./v1/philosophy.md
#   - Reference:
#       - API: ./v1/reference_api.md
#   - Change log:
#       - pydantic-resolve: ./v1/changelog.md

nav:
  - Quick Start:
      - Introduction: ./introduction.md
      - Use cases: ./use_case.md
      - Schema first: ./schema_first.md
      - Why create it: ./why.md
  - Features:
      - Dataloader: ./dataloader.md
      - Inherit and reuse: ./inherit_reuse.md
      - ERD Driven Pattern: ./erd_driven.md
      - Expose and collect: ./expose_and_collect.md
      - Connect to UI: ./connect_to_ui.md
  - API:
      - Reference: ./api.md
      - Change log: ./changelog.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.superfences

plugins:
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          default: true
          name: English
          build: true
          link: "/pydantic-resolve/"
        - locale: zh
          name: 中文
          build: true
          link: "/pydantic-resolve/zh/"
          nav_translations:
            Quick Start: "快速开始"
            Introduction: "简介"
            Use cases: "应用场景"
            Why create it: "为何写个新的库?"
            Schema first: "定义数据结构"
            Features: "功能介绍"
            Dataloader: "数据加载器"
            Inherit and reuse: "继承和复用"
            Expose and collect: "提供和收集"
            Reference: "文档"
            Connect to UI: "连接UI"
            ERD Driven Pattern: "ERD 驱动开发"
            Change log: "变更记录"
            Install: "安装"
            Let's start: "开始"
            Inheritance: "继承"
            Philosophy: "迷思"
